-- MySQL Script generated by MySQL Workbench
-- Wed Jan 29 18:02:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookshop` DEFAULT CHARACTER SET utf8 ;
USE `bookshop` ;

-- -----------------------------------------------------
-- Table `bookshop`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshop`.`Customer` (
  `custID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`custID`),
  UNIQUE INDEX `custID_UNIQUE` (`custID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookshop`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshop`.`User` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Customer_custID` INT,
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC) VISIBLE,
  PRIMARY KEY (`userID`),
  INDEX `fk_User_Customer1_idx` (`Customer_custID` ASC) VISIBLE,
  CONSTRAINT `fk_User_Customer1`
    FOREIGN KEY (`Customer_custID`)
    REFERENCES `bookshop`.`Customer` (`custID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookshop`.`Feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshop`.`Feedback` (
  `feedID` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(45) NULL,
  `rating` INT NOT NULL,
  `date` DATE NOT NULL,
  `User_userID` INT,
  PRIMARY KEY (`feedID`),
  UNIQUE INDEX `feedID_UNIQUE` (`feedID` ASC) VISIBLE,
  INDEX `fk_Feedback_User1_idx` (`User_userID` ASC) VISIBLE,
  CONSTRAINT `fk_Feedback_User1`
    FOREIGN KEY (`User_userID`)
    REFERENCES `bookshop`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookshop`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshop`.`Book` (
  `bookID` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `title_ganre` VARCHAR(45) DEFAULT 'unknown',
  `author` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `publish_house` VARCHAR(45) DEFAULT 'unknown',
  `avr_rating` DOUBLE NULL DEFAULT 0,
  `Feedback_feedID` INT,
  `Feedback_bookID` INT,
  `Ganre_ganreID` INT,
  PRIMARY KEY (`bookID`),
  UNIQUE INDEX `fk_Book_Feedback1_idx` (`Feedback_feedID` ASC, `Feedback_bookID` ASC) VISIBLE,
  INDEX `fk_Book_Ganre1_idx` (`Ganre_ganreID` ASC) VISIBLE,
  CONSTRAINT `fk_Book_Feedback1`
    FOREIGN KEY (`Feedback_feedID`)
    REFERENCES `bookshop`.`Feedback` (`feedID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_Ganre1`
    FOREIGN KEY (`Ganre_ganreID`)
    REFERENCES `bookshop`.`Ganre` (`ganreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookshop`.`Ganre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshop`.`Ganre` (
  `ganreID` INT NOT NULL AUTO_INCREMENT,
  `titleGanre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ganreID`),
  UNIQUE INDEX `ganreID_UNIQUE` (`ganreID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookshop`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshop`.`Order` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `sumOrder` DOUBLE NOT NULL,
  `counter` INT NOT NULL,
  `Customer_custID` INT NOT NULL,
  `Book_bookID` INT NOT NULL,
  PRIMARY KEY (`orderID`),
  UNIQUE INDEX `orderID_UNIQUE` (`orderID` ASC) VISIBLE,
  INDEX `fk_Order_Customer1_idx` (`Customer_custID` ASC) VISIBLE,
  INDEX `fk_Order_Book1_idx` (`Book_bookID` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`Customer_custID`)
    REFERENCES `bookshop`.`Customer` (`custID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Book1`
    FOREIGN KEY (`Book_bookID`)
    REFERENCES `bookshop`.`Book` (`bookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
